apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: shawarma
rules:
- apiGroups: [""]
  resources: ["endpoints"]
  verbs: ["get", "watch", "list"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: shawarma-example
subjects:
- kind: ServiceAccount
  name: shawarma-example
  namespace: default
roleRef:
  kind: ClusterRole
  name: shawarma
  apiGroup: rbac.authorization.k8s.io
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: shawarma-example
---
apiVersion: v1
kind: Service
metadata:
  name: shawarma-example
  labels:
    svc: shawarma-example
spec:
  selector:
    app: shawarma-example
    active: 'true'
  ports:
  - name: http
    port: 8080
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: shawarma-example
  labels:
    app: shawarma-example
spec:
  replicas: 2
  selector:
    matchLabels:
      app: shawarma-example
  template:
    metadata:
      labels:
        app: shawarma-example
        active: 'true'
      annotations:
        shawarma.centeredge.io/service-labels: svc=shawarma-example
    spec:
      serviceAccountName: shawarma-example
      containers:
        - name: primary
          # Simple HTTP server for example purposes, logs requests and responds with 200
          image: mendhak/http-https-echo
          ports:
          - name: http
            containerPort: 8080
          resources:
            requests:
              cpu: 100m
              memory: 64Mi
            limits:
              cpu: 100m
              memory: 64Mi
        - name: shawarma
          # Using latest is not recommended for production, specify a version number
          image: centeredge/shawarma:latest
          securityContext:
            allowPrivilegeEscalation: false
            seccompProfile:
              type: RuntimeDefault
            runAsNonRoot: true
          env:
            - name: LOG_LEVEL
              value: DEBUG
            - name: SHAWARMA_SERVICE
              # References service to monitor
              valueFrom:
                fieldRef:
                  fieldPath: metadata.annotations['shawarma.centeredge.io/service-name']
            - name: SHAWARMA_SERVICE_LABELS
              # References service to monitor
              valueFrom:
                fieldRef:
                  fieldPath: metadata.annotations['shawarma.centeredge.io/service-labels']
            - name: SHAWARMA_URL
              # Will POST state to this URL as pod is attached/detached from the service
              value: http://localhost:8080/applicationstate
            - name: MY_POD_NAME
              valueFrom:
                fieldRef:
                  fieldPath: metadata.name
            - name: MY_POD_NAMESPACE
              valueFrom:
                fieldRef:
                  fieldPath: metadata.namespace
          resources:
            requests:
              cpu: 10m
              memory: 64Mi
            limits:
              cpu: 10m
              memory: 64Mi
