# This file creates the sidecar injection webhook and the standard Shawarma cluster role
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: shawarma
rules:
- apiGroups: [""]
  resources: ["endpoints"]
  verbs: ["get", "watch", "list"]
---
apiVersion: v1
kind: Service
metadata:
  name: shawarma-webhook
  namespace: kube-system
  labels:
    k8s-app: shawarma-webhook
spec:
  type: ClusterIP
  ports:
  - name: https
    port: 443
    targetPort: https
    protocol: TCP
  selector:
    k8s-app: shawarma-webhook
---
# TLS certificate for the Shawarma webhook, replace this with your own certificates in production
# The signing CA must be placed in the MutatingWebhookConfiguration
apiVersion: v1
kind: Secret
metadata:
  name: shawarma-webhook
  namespace: kube-system
data:
  # Certificate file
  cert.pem: LS0tLS1CRUdJTiBDRVJUSUZJQ0FURS0tLS0tCk1JSUU3ekNDQXRlZ0F3SUJBZ0lVWTE0bVFvTDh3VHB1UTJYMkhVYU5tR0VrQU9zd0RRWUpLb1pJaHZjTkFRRUwKQlFBd2dhQXhDekFKQmdOVkJBWVRBbFZUTVJjd0ZRWURWUVFJREE1T2IzSjBhQ0JEWVhKdmJHbHVZVEVRTUE0RwpBMVVFQnd3SFVtOTRZbTl5YnpFY01Cb0dBMVVFQ2d3VFEyVnVkR1Z5UldSblpTQlRiMlowZDJGeVpURWNNQm9HCkExVUVBd3dUYzJoaGQyRnliV0V0ZDJWaWFHOXZheTFEUVRFcU1DZ0dDU3FHU0liM0RRRUpBUlliYm5Wc2JFQnoKYUdGM1lYSnRZUzVqWlc1MFpYSmxaR2RsTG1sdk1DQVhEVEU1TURjek1ERTFNREUwTTFvWUR6UTNOVGN3TmpJMQpNVFV3TVRReldqQnhNUXN3Q1FZRFZRUUdFd0pWVXpFWE1CVUdBMVVFQ0F3T1RtOXlkR2dnUTJGeWIyeHBibUV4CkVEQU9CZ05WQkFjTUIxSnZlR0p2Y204eEhEQWFCZ05WQkFvTUUwTmxiblJsY2tWa1oyVWdVMjltZEhkaGNtVXgKR1RBWEJnTlZCQU1NRUhOb1lYZGhjbTFoTFhkbFltaHZiMnN3Z2dFaU1BMEdDU3FHU0liM0RRRUJBUVVBQTRJQgpEd0F3Z2dFS0FvSUJBUUR4dFlpbDJEamRVOVEzK3FxdnBSbEdmSUZ3Y0xuVDlRUkdtU2hXeldINDZ0NjZSeXlsCkJ6UENwSDhYOUJ5ZzlRTkE4RE45TzJ5UHNlcy96SEZ4bnBkK0NnWE1tZDJxVG1iaEN4Ujl3RTZoQ2lEVjMvVFUKa04vdURwaGw4VzYzRmxrT3B0WXlMUHcxWTFwdzVoVFpPODNKdmhYNW82SVNmYi90ZkMwOWVmcTNhV1AwNC81NApMWjZmWi9PQWtxNVpKVlIybndpd0V3T0srUC9KcVRHVGZPME8zV2tKZFRsbnNoMWl3TWdCTHowR00wY3RQbDI2CldJd21FQWd0ZHg3UVRGQkZjT2tDRUNmZC9Ba08xS1JiNG54UkVZMTI0d3F2MTd6WWNrajlRUklrb3hzZkxFb2MKUmtnSGY1MDhFS1Z0N3dveHFHbXkrZGhHNmtSRjlrRW00cmpEQWdNQkFBR2pUVEJMTUVrR0ExVWRFUVJDTUVDQwpISE5vWVhkaGNtMWhMWGRsWW1odmIyc3VhM1ZpWlMxemVYTjBaVzJDSUhOb1lYZGhjbTFoTFhkbFltaHZiMnN1CmEzVmlaUzF6ZVhOMFpXMHVjM1pqTUEwR0NTcUdTSWIzRFFFQkN3VUFBNElDQVFCbnc5QmJNSzZhZms0RkVXSDMKM1pvVlhGOEZJK05yS1gyYmM5eStnZkVKUEpMTVhWRXZMU1N4TnlYd2tTai9mV3pEaDNvOVpHSmF1TFZyeWo4RwowaVZYOHBDeXExbElqUmp6SGsxSWYyc0ROSWVwOHNlNFpleTlWSklka0hnTVRJK1VEdUJQZ3VjT2hCQ2ZyRE5QCmVObHM5Z20wRldrOGU2UHI1eEViSmpYaTF0cVNnNXBOWGJ5cTNqNmYreldhM0NRekVFcE94aWw0NkYrakhmMnEKOHNubHhPaGhBM1ZSeG9qY0R1aXFBckxDWFBabDRhQzJIeTE2anV4R0VFdllNdFp3ZGxtbklGcWpMYlVsTHQ5bwpKKzhlNzF6YnR6V0V3NXVuMGQybXYwTERIeGJ3N05SRFduemZnYjBPL1RRcSs1ak9NdDhnTmVxdXRBZFp2MUNmCmdndHhwSENTU0xJRnYvVTRjamhySnZTOXRVV0ZQbFd0WDZTblVXeVgvK2tDSTdqYndYZ0ZEeFhXaHRLSjczdGIKYVhWV1dUcTBRYjlMYlVKR2lBcmRxM0FxbTZYazRIU2FEWlJvMFltNFNFd1I0ZHhtaUl6WGhqMkhWby9Pa3NrUApZYmVzU2tlbmZsdmJobWx2Sno2UHAvcFlEMUhnQ1JZcDB2Unpla2pYa2k2Uks4VmpIU0FRRmVBaE8xY3RiYVkyCmpBenpHc0E1b0NjRVhVVkVONWZNT1p3bHRmNGlzaFJZUFRxUGp1UTdkRHZpWlYvVXlSUis0WUtHendTM2g0VVkKOUNTcEJnVWpYM1dzRFRCZzRpL24yeUVEckZJcnNTUFZEdGIvMk8rMlBUKzhBV0J6Vjg4VS8xMjljckdkS3dCNwovK1FUdWtOdWFuaG9MZ2xkMmNWNWlONWlrZz09Ci0tLS0tRU5EIENFUlRJRklDQVRFLS0tLS0K
  # Private key
  key.pem: LS0tLS1CRUdJTiBSU0EgUFJJVkFURSBLRVktLS0tLQpNSUlFb3dJQkFBS0NBUUVBOGJXSXBkZzQzVlBVTi9xcXI2VVpSbnlCY0hDNTAvVUVScGtvVnMxaCtPcmV1a2NzCnBRY3p3cVIvRi9RY29QVURRUEF6ZlR0c2o3SHJQOHh4Y1o2WGZnb0Z6Sm5kcWs1bTRRc1VmY0JPb1FvZzFkLzAKMUpEZjdnNllaZkZ1dHhaWkRxYldNaXo4TldOYWNPWVUyVHZOeWI0VithT2lFbjIvN1h3dFBYbjZ0MmxqOU9QKwplQzJlbjJmemdKS3VXU1ZVZHA4SXNCTURpdmoveWFreGszenREdDFwQ1hVNVo3SWRZc0RJQVM4OUJqTkhMVDVkCnVsaU1KaEFJTFhjZTBFeFFSWERwQWhBbjNmd0pEdFNrVytKOFVSR05kdU1LcjllODJISkkvVUVTSktNYkh5eEsKSEVaSUIzK2RQQkNsYmU4S01haHBzdm5ZUnVwRVJmWkJKdUs0d3dJREFRQUJBb0lCQUIrakJTbS83V0Y2MFhJcQpTeUVHV1JLU3hWWjBTcjVsZVpQTUJDMm9ZRVIyYVlTMFFER3hpYUxXYVJRM2pXKzc0aHNqMVhsMHg3YmZNTTErCjh2Sk9NY0g3aWRySDRPMmpxVytYUmExWCtISzNvcWliMGEzbzhJWjJQcGhKUzVhSFJFellwWHlYeXNNcUovSlQKQ3pPTDBsbXZtYXk5TUQ5L1dobTVnU3BreHQ0dW1ob1NWVG1nWUk0YUZVVldUK0s3bUg3cmlUeGtad1NvYWFBRApyN0N6MTZqSDBkOFVEVS82by9QRzYvSDZ3MTZmdHE5MHpleFVlQnM4MmJhRmx5NUxIbG51ZTZGMU9ZNjlJeThECjJwemdVVVA5ZnJDS2hiQXZJaTZERDJ4U096YWJZQW9ZUXVaL0Vxb01Ndm9mdTlDY2hIYmR3aHdnY1dUZXVlTlgKMWJoOU5sRUNnWUVBK25OWENaUHh3MWdYWFZDaUwxUzArUDZ4THphSERZb015ZHFRbktJdEJHSG1Oa1lIWi84bwovWGZBeWk4Nm1oaE1kTU1mODhTYnp5MzYrWlFNYyttSCs0RDJ4YjFxMjBPakNwYmpkZW5tMWE5M0xWU1ZTOWJCCmlDcWFmWjJDQS93MWszMzVScWVtZHZaMmNuRzd5YldjSWU5ZUZSTnRDbGQ2UU1FVGNTZUU2azhDZ1lFQTl4Q2IKMXYxQk9SZllHSjgxb3pkdGRLUW9HWlRWc1ZUTS9GS2RvbHhZallPZUgvNmtMb1VnblNGS0libWtRYmR2SzBFZwo4SFk3bnZSNDhoWmRFVlFxVVdURjVQVENHUmY0SDVjdis5NDZmMmhIdjJUd1JKWTJUb2pNc2NsWURHYm5OcVpECmhHcjBxR0xJTWswbE9ydDZOWktmaVFoSkEzN2Mrd3FZSzlqWEVVMENnWUFPd0VSY0dBNmhSc3I1Z0FwTloxdlIKWG83cERQa2ZYd1lweldtL0QvNCt4OVZiVlB5U3I0Q21qU3NadlhaaUpSUTd2RkpoZFM4SUlOa3JZZ0Rwd3ROegppTUVBSEl2eXBpVXdObnJuTXdPWmltQW1sMWpEd3I1YldzY0dwd1JGWDlGNEFtOXdMZWVzRWhBZjVYcitBbWhUCngxbHZQRm1yeGtNNUZTWWtBQVBnR1FLQmdRQ21CanN6RmF5bXVTYzJKSWJlejNoMlVYbkE5d3RDeDBHWXJjdlEKTjA0cWlxL1B3RWFFSEdIMk5WQ2pxU1NBSk14SHZOUnR3b1grSXpyRE05UUd1UkJXOGVrcUdtLzBmTzc0QzVqcgpJRU1mS3V4TDZZQ3NGbVVZRVVXOGt4amYvS2FUU3RkRVBMdDhEQ1dMNTl1RXhFY3ppUHc4RVowL0JCbHJlWXNZCnEvYWFZUUtCZ0Vaa1JMRHdKQlNhUHpESlJtVTluSVNFM2diQjdmS2FYVjQvWGZDcVVwdEpUeEZpR2xodkdtZHgKUDVKK2hMNXNhOEttRU1YeU1UMG9zWE8yNkdBdE0zckRsRDk5WFRBYjl3d1BubVhpanUyeFBJclNUT0NPUDdRaQpBcmhNbHVUVk1tclBDNThNYU9TdDhUS0JzYjZxeFArV3hLSkQzV3ZhQjN4RmZ4M2lnNmZRCi0tLS0tRU5EIFJTQSBQUklWQVRFIEtFWS0tLS0tCg==
---
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: shawarma-webhook
  namespace: kube-system
  labels:
    k8s-app: shawarma-webhook
spec:
  replicas: 2
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 0
  template:
    metadata:
      labels:
        k8s-app: shawarma-webhook
    spec:
      volumes:
      - name: secrets
        secret:
          secretName: shawarma-webhook
      containers:
      - name: shawarma-webhook
        imagePullPolicy: Always
        image: centeredge/shawarma-webhook:0.1.0
        ports:
        - name: https
          containerPort: 443
        volumeMounts:
        - name: secrets
          mountPath: /etc/shawarma-webhook/certs
        livenessProbe:
          httpGet:
            scheme: HTTPS
            path: /health
            port: https
          initialDelaySeconds: 10
          periodSeconds: 10
          timeoutSeconds: 3
        resources:
          requests:
            cpu: "0.5"
            memory: 1Gi
          limits:
            cpu: "0.5"
            memory: 2Gi
---
apiVersion: admissionregistration.k8s.io/v1beta1
kind: MutatingWebhookConfiguration
metadata:
  name: shawarma-webhook
  labels:
    k8s-app: shawarma-webhook
webhooks:
- name: "webhook.shawarma.centeredge.io"
  failurePolicy: "Ignore" # we fail "open" if the webhook is down hard
  rules:
  - operations: [ "CREATE" ]
    apiGroups: [""]
    apiVersions: ["v1"]
    resources: ["pods"]
  clientConfig:
    service:
      name: shawarma-webhook
      namespace: kube-system
      path: "/mutate"
    # Signing CA for the certificate placed in the secret above
    caBundle: "LS0tLS1CRUdJTiBDRVJUSUZJQ0FURS0tLS0tCk1JSUZ5ekNDQTdNQ0ZHWHhDbjVNSi9QcFNKSlIveEFHSFVPS1VudUtNQTBHQ1NxR1NJYjNEUUVCQ3dVQU1JR2cKTVFzd0NRWURWUVFHRXdKVlV6RVhNQlVHQTFVRUNBd09UbTl5ZEdnZ1EyRnliMnhwYm1FeEVEQU9CZ05WQkFjTQpCMUp2ZUdKdmNtOHhIREFhQmdOVkJBb01FME5sYm5SbGNrVmtaMlVnVTI5bWRIZGhjbVV4SERBYUJnTlZCQU1NCkUzTm9ZWGRoY20xaExYZGxZbWh2YjJzdFEwRXhLakFvQmdrcWhraUc5dzBCQ1FFV0cyNTFiR3hBYzJoaGQyRnkKYldFdVkyVnVkR1Z5WldSblpTNXBiekFnRncweE9UQTNNekF4TlRBeE5EQmFHQTgwTnpVM01EWXlOVEUxTURFMApNRm93Z2FBeEN6QUpCZ05WQkFZVEFsVlRNUmN3RlFZRFZRUUlEQTVPYjNKMGFDQkRZWEp2YkdsdVlURVFNQTRHCkExVUVCd3dIVW05NFltOXliekVjTUJvR0ExVUVDZ3dUUTJWdWRHVnlSV1JuWlNCVGIyWjBkMkZ5WlRFY01Cb0cKQTFVRUF3d1RjMmhoZDJGeWJXRXRkMlZpYUc5dmF5MURRVEVxTUNnR0NTcUdTSWIzRFFFSkFSWWJiblZzYkVCegphR0YzWVhKdFlTNWpaVzUwWlhKbFpHZGxMbWx2TUlJQ0lqQU5CZ2txaGtpRzl3MEJBUUVGQUFPQ0FnOEFNSUlDCkNnS0NBZ0VBclU5YTl6SFZLV2NCaEZvc00wZWp6ZzhraUNrUXl0cmVmSC9yWUwxNldwRkwxZ3ZDUkQ4RmRUZGgKdXp4NE91eVEwa2FwOENQSGY4YkovdUgyNU5ZTVBlRzBtZjRhUFdXSU9lU0FYbEVnTGd4OVI5alpnUEFTZDhXZQphNmdzOWdxZjk5VXkrNVlxTjZVVmU3bEhMSnlBUHhCVkY3SmRZbUIrR29KUVBKd2RNYjZBVzk3aFhKdmswSCthClkrQllVL3pRbkJlYXBTU1I5QjZwbis1SUdRWmNHN1ZkMkN4dm1qdGVoVmZ4NXE4cHpYazdKeDBnQ29hcUlBb2YKSWJpaWlWQVZKNkt6Tms0cUdxZlNwVzhxaWFPTFpUWUxkL2RVZVBvSnRwSHd2a3NrWU1OZ3gybUtsWVZjMGRSQgpNeU9URHdNMFZBbnNxZFZMVDg2eFRNWkl5UWMzZzczZ0ExR092YnhSbFBzcWFKbG40cE5lY21ZYlRyKzY3TXd3CnRkT2lzYXhBRlp1VVJjU3o5Zk9ENjlFdmVCcnNQUlR2MVZGVndielRkSFhsS0NFcFBEeUx2QTNrZWFFa3FRb24KT3F5RWhFa2x5MTE5dFRCaVFLOW5DNnlDTEtpemFZZVNxWHNRSDB1SGZVcElFUmVhaGxGRHQwRVZjOGViVEFRKwpIV3F5aXV1bUs1RnBESFNoRWxmeFRsQVNzc3ZSVVdkZXpIdjlCa2NjWTB4MHg1TWFwLy9TTFJhbW9SeWVWLys0CjUzcFVsUGtpS1Z0L3E0OFJwVVdWZFRaaWtFNExlcXZmUS9vOHF2ZG12WUljOXJIeGhSeG9yVGs0QjJxUWc4MzcKNmlmQWY0L1RSb0w0MnBYSWZMREh5K0RYNkRGRnJPN1FRS2YrNm01R243aXM2WXYxNnNVQ0F3RUFBVEFOQmdrcQpoa2lHOXcwQkFRc0ZBQU9DQWdFQUhleTMwVWRkTFp1NFZsM3c5L3BBMHd6QlpZNlR3WFdWRUd3cWZ5UmtXY0ozCmdMRmRGdFVzZVJIUGdvMk95ZHNmNHZObEFqelI2N0V2c2NxbFhpNXg5ZVo3a01Zd2lvNmllL0JxN241ZHZ0clgKdFhqM3Jra2s4NC9qY25IbTQ0cjRPRW5KeG9VZWVDZXROTThEdTBuSjJTMStqQXFlNExiWDB4akRMbjU2cE0wdgpvTXE2ekNWWnJKMUQrdE4zOWNuRlBkNmN3V2tqYmRUVE16ZmFPTjJxelpkdDRJOThLQ0YvdlR1cUxZdFdPTW5hCnBYSlgzTWY4SnlKUjFqVmtsU2FsY0FyRUkzYlNiUzNoR0NWZ2RHczBKVWJlNXVTUGNXYjdKbDY4K29sNGtpcUUKekxkenQzSG8yVC9VVWZBVHpZQk5rZlNpczloa3NlK1NJdWtYVzBpV0N5RndQR3dzTjByTDUrcFdwNTVJR3BYOQp4VHcxQlZ2STdVTUNaaUJXeGFJMXNQV3o3MlRKc3o4TEl1ZUtsVTVweFRNb1RBdXBXZHJLamtMSi9jMTYrUFJ5CkkxR2t2QUZBQklxMkpHR3gxZ3hPMXQ0VVhjMHJNampRVStkZnhOekRqUFJBWmlSUnpTazJuRmJaYUZrMUN1ekwKTTlxcDVaRDc1c2VZOUI3ZmRRVnNGMUVpblhESXNpM29pZFphRzNzd05kRVFwYWVjOGVMcWFZcUp3RkpzL1NkcQozdzlsRHlvc2RXdDRXWSsxaWc5Q2RyVVByWUFVd0s2Q1dJVjRkQnRScXVuazc1TmxaOUpEQXgwR2RlOEl1N29qCk8yZ1ovZVhIQjFVcWZKa3FmNW55V2RiNGhZR1pZUXAwUGRsU1NrZ1Q4MmE2aDZWQ3FpNUxGRU85eVI1M3JWcz0KLS0tLS1FTkQgQ0VSVElGSUNBVEUtLS0tLQo="
